/**
 * @file    main.c
 * @brief   OBC main entry point
 *
 * This file handles:
 *   1. HAL and peripheral initialisation (generated by CubeMX)
 *   2. Sensor driver initialisation
 *   3. FatFS initialisation
 *   4. Scheduler and task creation
 *   5. FreeRTOS scheduler start
 *
 * CubeMX-generated peripheral init code (MX_xxx_Init functions)
 * should be placed in the USER CODE sections below.
 * Do not modify generated code outside of USER CODE blocks.
 */

#include "main.h"
#include "obc_config.h"
#include "scheduler.h"
#include "mpu6050.h"
#include "hmc5883l.h"
#include "fatfs.h"

/* =========================================================
 * HAL PERIPHERAL HANDLES
 * These are defined here and extern-referenced by obc_config.h
 * ========================================================= */
I2C_HandleTypeDef  hi2c1;
SPI_HandleTypeDef  hspi1;
SPI_HandleTypeDef  hspi2;
SPI_HandleTypeDef  hspi3;
UART_HandleTypeDef huart2;
ADC_HandleTypeDef  hadc1;

/* =========================================================
 * FORWARD DECLARATIONS (CubeMX-generated)
 * ========================================================= */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_SPI1_Init(void);
static void MX_SPI2_Init(void);
static void MX_SPI3_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_ADC1_Init(void);

/* =========================================================
 * MAIN
 * ========================================================= */
int main(void)
{
    /* --------------------------------------------------
     * 1. HAL init and clock configuration
     * -------------------------------------------------- */
    HAL_Init();
    SystemClock_Config();   /* Configure 168 MHz SYSCLK */

    /* --------------------------------------------------
     * 2. Peripheral initialisation (CubeMX-generated)
     * -------------------------------------------------- */
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_SPI1_Init();
    MX_SPI2_Init();
    MX_SPI3_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();

    /* --------------------------------------------------
     * 3. Sensor driver initialisation
     * -------------------------------------------------- */

    /* MPU6050: +/- 250 deg/s gyro, +/- 2g accel (tune for mission) */
    if (MPU6050_Init(&ADCS_I2C_HANDLE,
                      MPU6050_ACCEL_FS_2G,
                      MPU6050_GYRO_FS_250) != HAL_OK) {
        /* Sensor init failure -- raise fault before scheduler starts */
        /* Cannot call FDIR_RaiseFault yet (RTOS not running).
         * Log to a global pre-RTOS error variable instead. */
    }

    /* HMC5883L magnetometer: +/- 1.3 Gauss (default) */
    if (HMC5883L_Init(&ADCS_I2C_HANDLE, HMC_GAIN_1_3) != HAL_OK) {
        /* Same handling as above */
    }

    /* --------------------------------------------------
     * 4. FatFS initialisation
     *    MX_FATFS_Init() is CubeMX-generated.
     * -------------------------------------------------- */
    MX_FATFS_Init();

    /* --------------------------------------------------
     * 5. Create all tasks and start scheduler
     * -------------------------------------------------- */
    Scheduler_Init();

    /* vTaskStartScheduler() should not return.
     * If it does, the heap is too small or stack overflow occurred. */
    vTaskStartScheduler();

    /* Should never reach here */
    while (1) {}
}

/* =========================================================
 * PERIPHERAL INIT STUBS
 * Replace with CubeMX-generated implementations.
 * These are intentionally left as stubs here.
 * ========================================================= */

static void SystemClock_Config(void)
{
    /*
     * Configure PLL for 168 MHz from 8 MHz HSE (Discovery board).
     * Generate this in CubeMX: System Core -> RCC -> HSE = Crystal,
     * then set HCLK to 168 MHz.
     */
}

static void MX_GPIO_Init(void)
{
    /* Configure CS pins as outputs, push-pull, no pull */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;

    /* Comms CS */
    gpio.Pin = COMMS_CS_PIN;
    HAL_GPIO_Init(COMMS_CS_PORT, &gpio);
    HAL_GPIO_WritePin(COMMS_CS_PORT, COMMS_CS_PIN, GPIO_PIN_SET);

    /* Payload CS */
    gpio.Pin = PAYLOAD_CS_PIN;
    HAL_GPIO_Init(PAYLOAD_CS_PORT, &gpio);
    HAL_GPIO_WritePin(PAYLOAD_CS_PORT, PAYLOAD_CS_PIN, GPIO_PIN_SET);

    /* SD card CS */
    gpio.Pin = SDCARD_CS_PIN;
    HAL_GPIO_Init(SDCARD_CS_PORT, &gpio);
    HAL_GPIO_WritePin(SDCARD_CS_PORT, SDCARD_CS_PIN, GPIO_PIN_SET);
}

static void MX_I2C1_Init(void)
{
    hi2c1.Instance              = I2C1;
    hi2c1.Init.ClockSpeed       = 400000;   /* 400 kHz fast mode */
    hi2c1.Init.DutyCycle        = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1      = 0;
    hi2c1.Init.AddressingMode   = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode  = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode  = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode    = I2C_NOSTRETCH_DISABLE;
    HAL_I2C_Init(&hi2c1);
}

static void MX_SPI1_Init(void)
{
    hspi1.Instance               = SPI1;
    hspi1.Init.Mode              = SPI_MODE_MASTER;
    hspi1.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi1.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi1.Init.CLKPolarity       = SPI_POLARITY_LOW;
    hspi1.Init.CLKPhase          = SPI_PHASE_1EDGE;
    hspi1.Init.NSS               = SPI_NSS_SOFT;
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_64; /* ~1.3 MHz */
    hspi1.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    HAL_SPI_Init(&hspi1);
}

static void MX_SPI2_Init(void)
{
    hspi2.Instance               = SPI2;
    hspi2.Init.Mode              = SPI_MODE_MASTER;
    hspi2.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi2.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi2.Init.CLKPolarity       = SPI_POLARITY_LOW;
    hspi2.Init.CLKPhase          = SPI_PHASE_1EDGE;
    hspi2.Init.NSS               = SPI_NSS_SOFT;
    hspi2.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_64;
    hspi2.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    HAL_SPI_Init(&hspi2);
}

static void MX_SPI3_Init(void)
{
    /* SD card SPI -- can run faster once verified */
    hspi3.Instance               = SPI3;
    hspi3.Init.Mode              = SPI_MODE_MASTER;
    hspi3.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi3.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi3.Init.CLKPolarity       = SPI_POLARITY_LOW;
    hspi3.Init.CLKPhase          = SPI_PHASE_1EDGE;
    hspi3.Init.NSS               = SPI_NSS_SOFT;
    hspi3.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32;
    hspi3.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    HAL_SPI_Init(&hspi3);
}

static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 9600;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart2);
}

static void MX_ADC1_Init(void)
{
    hadc1.Instance                   = ADC1;
    hadc1.Init.ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4;
    hadc1.Init.Resolution            = ADC_RESOLUTION_12B;
    hadc1.Init.ScanConvMode          = DISABLE;
    hadc1.Init.ContinuousConvMode    = DISABLE;
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.ExternalTrigConv      = ADC_SOFTWARE_START;
    hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc1.Init.NbrOfConversion       = 1;
    hadc1.Init.DMAContinuousRequests = DISABLE;
    hadc1.Init.EOCSelection          = ADC_EOC_SINGLE_CONV;
    HAL_ADC_Init(&hadc1);
}

/* =========================================================
 * FREERTOS STACK OVERFLOW HOOK
 * ========================================================= */
void vApplicationStackOverflowHook(TaskHandle_t xTask,
                                    char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    /*
     * Stack overflow detected.
     * In production: log fault, reset via IWDG.
     * For EM debug: halt here so debugger catches it.
     */
    __disable_irq();
    while (1) {}
}

/* =========================================================
 * FREERTOS MALLOC FAILED HOOK
 * ========================================================= */
void vApplicationMallocFailedHook(void)
{
    __disable_irq();
    while (1) {}
}
